language: php
php:
 - '7.2'
 - '7.3'
 - '7.4'

branches:
  only:
    - master


before_script:
  - sudo apt-get update
  - composer install --dev


script: phpunit --configuration phpunit.xml --coverage-clover ./build/logs/clover.xml

after_success:
  - travis_retry php vendor/bin/php-coveralls -v